package com.spirit.shit.global.entity.animation.entities;

import net.minecraft.client.render.entity.animation.Animation;
import net.minecraft.client.render.entity.animation.AnimationHelper;
import net.minecraft.client.render.entity.animation.Keyframe;
import net.minecraft.client.render.entity.animation.Transformation;

public class RatAnimations {
    @SuppressWarnings("unused")
    public static void FileContents() {
        Animation ratIdle = RatAnimations.RAT_IDLE;
        Animation ratMove = RatAnimations.RAT_MOVE;
        Animation ratSpin = RatAnimations.RAT_SPIN;

    }

    public static final Animation RAT_IDLE = Animation.Builder.create(4f).looping()
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_ear",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_ear",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.2916767f, AnimationHelper.createRotationalVector(2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5416765f, AnimationHelper.createRotationalVector(-2.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation RAT_MOVE = Animation.Builder.create(0.3433333f).looping()
            .addBoneAnimation("body",
                    new Transformation(Transformation.Targets.SCALE,
                            new Keyframe(0f, AnimationHelper.createScalingVector(1f, 1f, 1f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("head",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(7.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("tail",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(-7.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("right_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(27.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR)))
            .addBoneAnimation("left_leg",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.08343333f, AnimationHelper.createRotationalVector(-20f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.16766666f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.25f, AnimationHelper.createRotationalVector(27.5f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.3433333f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
    public static final Animation RAT_SPIN = Animation.Builder.create(32f).looping()
            .addBoneAnimation("root",
                    new Transformation(Transformation.Targets.ROTATE,
                            new Keyframe(0f, AnimationHelper.createRotationalVector(0f, 0f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(0.5f, AnimationHelper.createRotationalVector(0f, 90f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1f, AnimationHelper.createRotationalVector(0f, 180f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(1.5f, AnimationHelper.createRotationalVector(0f, 270f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2f, AnimationHelper.createRotationalVector(0f, 360f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(2.5f, AnimationHelper.createRotationalVector(0f, 450f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3f, AnimationHelper.createRotationalVector(0f, 540f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(3.5f, AnimationHelper.createRotationalVector(0f, 630f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4f, AnimationHelper.createRotationalVector(0f, 720f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(4.5f, AnimationHelper.createRotationalVector(0f, 810f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5f, AnimationHelper.createRotationalVector(0f, 900f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(5.5f, AnimationHelper.createRotationalVector(0f, 990f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6f, AnimationHelper.createRotationalVector(0f, 1080f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(6.5f, AnimationHelper.createRotationalVector(0f, 1170f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7f, AnimationHelper.createRotationalVector(0f, 1260f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(7.5f, AnimationHelper.createRotationalVector(0f, 1350f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(8f, AnimationHelper.createRotationalVector(0f, 1440f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(8.5f, AnimationHelper.createRotationalVector(0f, 1530f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(9f, AnimationHelper.createRotationalVector(0f, 1620f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(9.5f, AnimationHelper.createRotationalVector(0f, 1710f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(10f, AnimationHelper.createRotationalVector(0f, 1800f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(10.5f, AnimationHelper.createRotationalVector(0f, 1890f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(11f, AnimationHelper.createRotationalVector(0f, 1980f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(11.5f, AnimationHelper.createRotationalVector(0f, 2070f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(12f, AnimationHelper.createRotationalVector(0f, 2160f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(12.5f, AnimationHelper.createRotationalVector(0f, 2250f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(13f, AnimationHelper.createRotationalVector(0f, 2340f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(13.5f, AnimationHelper.createRotationalVector(0f, 2430f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(14f, AnimationHelper.createRotationalVector(0f, 2520f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(14.5f, AnimationHelper.createRotationalVector(0f, 2610f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(15f, AnimationHelper.createRotationalVector(0f, 2700f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(15.5f, AnimationHelper.createRotationalVector(0f, 2790f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(16f, AnimationHelper.createRotationalVector(0f, 2880f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(16.5f, AnimationHelper.createRotationalVector(0f, 2970f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(17f, AnimationHelper.createRotationalVector(0f, 3060f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(17.5f, AnimationHelper.createRotationalVector(0f, 3150f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(18f, AnimationHelper.createRotationalVector(0f, 3240f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(18.5f, AnimationHelper.createRotationalVector(0f, 3330f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(19f, AnimationHelper.createRotationalVector(0f, 3420f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(19.5f, AnimationHelper.createRotationalVector(0f, 3510f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(20f, AnimationHelper.createRotationalVector(0f, 3600f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(20.5f, AnimationHelper.createRotationalVector(0f, 3690f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(21f, AnimationHelper.createRotationalVector(0f, 3780f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(21.5f, AnimationHelper.createRotationalVector(0f, 3870f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(22f, AnimationHelper.createRotationalVector(0f, 3960f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(22.5f, AnimationHelper.createRotationalVector(0f, 4050f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(23f, AnimationHelper.createRotationalVector(0f, 4140f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(23.5f, AnimationHelper.createRotationalVector(0f, 4230f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(24f, AnimationHelper.createRotationalVector(0f, 4320f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(24.5f, AnimationHelper.createRotationalVector(0f, 4410f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(25f, AnimationHelper.createRotationalVector(0f, 4500f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(25.5f, AnimationHelper.createRotationalVector(0f, 4590f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(26f, AnimationHelper.createRotationalVector(0f, 4680f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(26.5f, AnimationHelper.createRotationalVector(0f, 4770f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(27f, AnimationHelper.createRotationalVector(0f, 4860f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(27.5f, AnimationHelper.createRotationalVector(0f, 4950f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(28f, AnimationHelper.createRotationalVector(0f, 5040f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(28.5f, AnimationHelper.createRotationalVector(0f, 5130f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(29f, AnimationHelper.createRotationalVector(0f, 5220f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(29.5f, AnimationHelper.createRotationalVector(0f, 5310f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(30f, AnimationHelper.createRotationalVector(0f, 5400f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(30.5f, AnimationHelper.createRotationalVector(0f, 5490f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(31f, AnimationHelper.createRotationalVector(0f, 5580f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(31.5f, AnimationHelper.createRotationalVector(0f, 5670f, 0f),
                                    Transformation.Interpolations.LINEAR),
                            new Keyframe(32f, AnimationHelper.createRotationalVector(0f, 5760f, 0f),
                                    Transformation.Interpolations.LINEAR))).build();
}